import { AbsoluteFill } from "remotion";
import React from "react";
import { BallEscape } from "./BallEscape";
import { TikTokComment } from "./TikTokComment/TikTokComment";
import { useAutoGeneratedComment } from "../hooks/useAutoGeneratedComment";

/**
 * Composition BallEscape enrichie avec commentaires TikTok auto-générés
 */
export const BallEscapeWithComments: React.FC = () => {
  // Générer automatiquement un commentaire TikTok à chaque rafraîchissement
  const commentData = useAutoGeneratedComment();

  return (
    <AbsoluteFill>
      {/* Composition principale BallEscape */}
      <BallEscape />

      {/* Overlay pour améliorer la lisibilité */}
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background:
            "linear-gradient(to bottom, transparent 60%, rgba(0,0,0,0.1) 90%)",
          pointerEvents: "none",
          zIndex: 5,
        }}
      />

      {/* Commentaire TikTok auto-généré */}
      {!commentData.isLoading && !commentData.error && (
        <TikTokComment
          imagePath={commentData.imagePath}
          x={0.05}
          y={0.7}
          scale={1.2}
          startFrame={60} // Commence après 2 secondes
          duration={300} // Dure 10 secondes
          animationType="slideIn"
          animationDuration={45}
          rotation={-1}
          className="auto-generated-comment"
        />
      )}

      {/* Indicateur de chargement */}
      {commentData.isLoading && (
        <div
          style={{
            position: "absolute",
            bottom: 100,
            left: 20,
            color: "white",
            fontSize: 12,
            fontFamily: "system-ui",
            backgroundColor: "rgba(0,0,0,0.7)",
            padding: "8px 12px",
            borderRadius: "6px",
            display: "flex",
            alignItems: "center",
            gap: "8px",
            zIndex: 15,
          }}
        >
          <div
            style={{
              width: "12px",
              height: "12px",
              border: "2px solid transparent",
              borderTop: "2px solid white",
              borderRadius: "50%",
              animation: "spin 1s linear infinite",
            }}
          />
          Génération du commentaire...
        </div>
      )}

      {/* Indicateur d'erreur */}
      {commentData.error && (
        <div
          style={{
            position: "absolute",
            bottom: 100,
            left: 20,
            color: "#ff6b6b",
            fontSize: 12,
            fontFamily: "system-ui",
            backgroundColor: "rgba(0,0,0,0.7)",
            padding: "8px 12px",
            borderRadius: "6px",
            maxWidth: "300px",
            zIndex: 15,
          }}
        >
          ❌ Erreur: {commentData.error}
        </div>
      )}

      {/* Métadonnées du commentaire généré */}
      {commentData.username && commentData.comment && (
        <div
          style={{
            position: "absolute",
            top: 20,
            right: 20,
            color: "white",
            fontSize: 10,
            fontFamily: "system-ui",
            backgroundColor: "rgba(0,0,0,0.5)",
            padding: "4px 8px",
            borderRadius: "4px",
            opacity: 0.7,
            maxWidth: "200px",
            zIndex: 15,
          }}
        >
          <div style={{ fontWeight: "bold" }}>@{commentData.username}</div>
          <div style={{ marginTop: "2px", fontSize: "9px" }}>
            {commentData.comment.slice(0, 50)}...
          </div>
        </div>
      )}

      {/* Filigrane amélioré */}
      <div
        style={{
          position: "absolute",
          bottom: 20,
          left: 20,
          color: "white",
          fontSize: 14,
          fontFamily: "system-ui, sans-serif",
          fontWeight: "bold",
          textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
          opacity: 0.9,
          zIndex: 10,
        }}
      >
        📱 TikTok Auto • Commentaire généré
      </div>
    </AbsoluteFill>
  );
};

export default BallEscapeWithComments;