import { useState, useEffect } from "react";

interface CommentData {
  imagePath: string;
  username: string;
  comment: string;
  isLoading: boolean;
  error: string | null;
}

/**
 * Hook pour générer automatiquement un commentaire TikTok
 * Se déclenche à chaque rafraîchissement de Remotion Studio
 */
export function useAutoGeneratedComment(): CommentData {
  const [commentData, setCommentData] = useState<CommentData>({
    imagePath: "/generated/tiktok-comment-current.png",
    username: "",
    comment: "",
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    // Fonction pour générer un nouveau commentaire
    const generateComment = async () => {
      try {
        setCommentData(prev => ({
          ...prev,
          isLoading: true,
          error: null,
        }));

        console.log("🎬 Génération automatique d'un commentaire TikTok...");

        const response = await fetch("/api/generate-tiktok-comment", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            maxRetries: 2, // Moins de tentatives pour éviter les délais
          }),
        });

        if (!response.ok) {
          throw new Error(`Erreur HTTP: ${response.status}`);
        }

        const result = await response.json();

        if (result.success) {
          setCommentData({
            imagePath: result.data.imagePath,
            username: result.data.username,
            comment: result.data.comment,
            isLoading: false,
            error: null,
          });
          console.log("✅ Commentaire généré avec succès:", result.data);
        } else {
          throw new Error(result.error || "Erreur lors de la génération");
        }
      } catch (error) {
        console.error("❌ Erreur lors de la génération automatique:", error);
        setCommentData(prev => ({
          ...prev,
          isLoading: false,
          error: error instanceof Error ? error.message : "Erreur inconnue",
        }));
      }
    };

    // Générer immédiatement au montage
    generateComment();

    // Optionnel: Régénérer périodiquement (pour le développement)
    const interval = setInterval(generateComment, 30000); // Toutes les 30 secondes

    return () => {
      clearInterval(interval);
    };
  }, []); // Se déclenche uniquement au montage (rafraîchissement)

  return commentData;
}

/**
 * Hook pour générer un commentaire avec déclenchement manuel
 */
export function useManualGeneratedComment() {
  const [commentData, setCommentData] = useState<CommentData>({
    imagePath: "/generated/tiktok-comment-current.png",
    username: "",
    comment: "",
    isLoading: false,
    error: null,
  });

  const generateComment = async () => {
    try {
      setCommentData(prev => ({
        ...prev,
        isLoading: true,
        error: null,
      }));

      const response = await fetch("/api/generate-tiktok-comment", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          maxRetries: 3,
        }),
      });

      if (!response.ok) {
        throw new Error(`Erreur HTTP: ${response.status}`);
      }

      const result = await response.json();

      if (result.success) {
        setCommentData({
          imagePath: result.data.imagePath,
          username: result.data.username,
          comment: result.data.comment,
          isLoading: false,
          error: null,
        });
      } else {
        throw new Error(result.error || "Erreur lors de la génération");
      }
    } catch (error) {
      setCommentData(prev => ({
        ...prev,
        isLoading: false,
        error: error instanceof Error ? error.message : "Erreur inconnue",
      }));
    }
  };

  return {
    ...commentData,
    generateComment,
  };
}

export default useAutoGeneratedComment;