"use client";

import { Player } from "@remotion/player";
import { BallEscape } from "../remotion/BallEscape";
import { GAME_CONFIG } from "../constants/game";
import { useAutoGeneratedComment } from "../hooks/useAutoGeneratedComment";

export default function Home() {
  const { isGenerating, isSuccess, error, commentData, regenerate } = useAutoGeneratedComment();

  return (
    <main className="min-h-screen bg-gray-900 flex flex-col items-center justify-center p-4">
      <h1 className="text-4xl font-bold text-white mb-4">
        Ball Escape Preview
      </h1>

      {/* Statut de génération du commentaire */}
      <div className="mb-6 max-w-3xl w-full">
        <div className="bg-gray-800 rounded-lg p-4 border-l-4 border-blue-500">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              {isGenerating && (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  <span className="text-white font-medium">Génération du commentaire TikTok...</span>
                </>
              )}
              
              {isSuccess && commentData && (
                <>
                  <div className="h-5 w-5 bg-green-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <div>
                    <span className="text-green-400 font-medium">Commentaire généré !</span>
                    <div className="text-gray-300 text-sm mt-1">
                      <span className="font-semibold">{commentData.username}</span>: "{commentData.comment}"
                    </div>
                  </div>
                </>
              )}
              
              {error && (
                <>
                  <div className="h-5 w-5 bg-red-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-xs">✗</span>
                  </div>
                  <div>
                    <span className="text-red-400 font-medium">Erreur de génération</span>
                    <div className="text-gray-300 text-sm mt-1">{error}</div>
                  </div>
                </>
              )}
            </div>
            
            <button
              onClick={regenerate}
              disabled={isGenerating}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 text-white rounded-lg text-sm font-medium transition-colors"
            >
              {isGenerating ? 'Génération...' : 'Régénérer'}
            </button>
          </div>
        </div>
      </div>

      {/* Player Remotion */}
      <div className="w-full max-w-3xl aspect-[9/16] bg-black rounded-lg overflow-hidden shadow-2xl">
        <Player
          component={BallEscape}
          durationInFrames={GAME_CONFIG.DURATION_IN_SECONDS * GAME_CONFIG.FPS}
          compositionWidth={GAME_CONFIG.VIDEO_WIDTH}
          compositionHeight={GAME_CONFIG.VIDEO_HEIGHT}
          fps={GAME_CONFIG.FPS}
          style={{
            width: "100%",
            height: "100%",
          }}
          controls
          autoPlay
          loop
        />
      </div>

      {/* Instructions */}
      <div className="mt-8 max-w-3xl text-gray-300 space-y-4">
        <h2 className="text-2xl font-semibold text-white">Comment jouer :</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            Regardez les balles "Yes" et "No" se déplacer à travers les cercles
          </li>
          <li>
            Chaque fois qu'une balle traverse un cercle, il explose et le score
            augmente
          </li>
          <li>Les collisions produisent des sons MIDI</li>
          <li>Le jeu dure {GAME_CONFIG.DURATION_IN_SECONDS} secondes</li>
          <li>À la fin, le gagnant est déterminé par le plus grand score</li>
          <li className="text-blue-400 font-medium">
            💡 Un nouveau commentaire TikTok est généré automatiquement à chaque chargement !
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-white mt-6">
          Pour exporter la vidéo :
        </h2>
        <pre className="bg-gray-800 p-4 rounded-lg overflow-x-auto">
          <code>
            npx remotion render src/remotion/Root.tsx BallEscape out/video.mp4
          </code>
        </pre>
      </div>
    </main>
  );
}
